// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: user/user/v1/user.proto

package userv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitUserRequest) Reset() {
	*x = InitUserRequest{}
	mi := &file_user_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitUserRequest) ProtoMessage() {}

func (x *InitUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitUserRequest.ProtoReflect.Descriptor instead.
func (*InitUserRequest) Descriptor() ([]byte, []int) {
	return file_user_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *InitUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type InitUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	InitializedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=initialized_at,json=initializedAt,proto3" json:"initialized_at,omitempty"` // User initialization timestamp
	SyncCode      string                 `protobuf:"bytes,3,opt,name=sync_code,json=syncCode,proto3" json:"sync_code,omitempty"`                // Sync code for tracking
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitUserResponse) Reset() {
	*x = InitUserResponse{}
	mi := &file_user_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitUserResponse) ProtoMessage() {}

func (x *InitUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitUserResponse.ProtoReflect.Descriptor instead.
func (*InitUserResponse) Descriptor() ([]byte, []int) {
	return file_user_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *InitUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InitUserResponse) GetInitializedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.InitializedAt
	}
	return nil
}

func (x *InitUserResponse) GetSyncCode() string {
	if x != nil {
		return x.SyncCode
	}
	return ""
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_user_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_user_user_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"` // User deletion timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_user_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_user_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteUserResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type IsActiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsActiveRequest) Reset() {
	*x = IsActiveRequest{}
	mi := &file_user_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsActiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsActiveRequest) ProtoMessage() {}

func (x *IsActiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsActiveRequest.ProtoReflect.Descriptor instead.
func (*IsActiveRequest) Descriptor() ([]byte, []int) {
	return file_user_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *IsActiveRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type IsActiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsActive      bool                   `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`   // Indicates if the user is active
	CheckedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"` // Timestamp when the check was performed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsActiveResponse) Reset() {
	*x = IsActiveResponse{}
	mi := &file_user_user_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsActiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsActiveResponse) ProtoMessage() {}

func (x *IsActiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsActiveResponse.ProtoReflect.Descriptor instead.
func (*IsActiveResponse) Descriptor() ([]byte, []int) {
	return file_user_user_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *IsActiveResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IsActiveResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *IsActiveResponse) GetCheckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedAt
	}
	return nil
}

type IsBlockedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsBlockedRequest) Reset() {
	*x = IsBlockedRequest{}
	mi := &file_user_user_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsBlockedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsBlockedRequest) ProtoMessage() {}

func (x *IsBlockedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsBlockedRequest.ProtoReflect.Descriptor instead.
func (*IsBlockedRequest) Descriptor() ([]byte, []int) {
	return file_user_user_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *IsBlockedRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type IsBlockedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsBlocked     bool                   `protobuf:"varint,2,opt,name=is_blocked,json=isBlocked,proto3" json:"is_blocked,omitempty"` // Indicates if the user is blocked
	CheckedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`  // Timestamp when the check was performed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsBlockedResponse) Reset() {
	*x = IsBlockedResponse{}
	mi := &file_user_user_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsBlockedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsBlockedResponse) ProtoMessage() {}

func (x *IsBlockedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsBlockedResponse.ProtoReflect.Descriptor instead.
func (*IsBlockedResponse) Descriptor() ([]byte, []int) {
	return file_user_user_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *IsBlockedResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IsBlockedResponse) GetIsBlocked() bool {
	if x != nil {
		return x.IsBlocked
	}
	return false
}

func (x *IsBlockedResponse) GetCheckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckedAt
	}
	return nil
}

var File_user_user_v1_user_proto protoreflect.FileDescriptor

const file_user_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x17user/user/v1/user.proto\x12\fuser.user.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#third_party/validate/validate.proto\"4\n" +
	"\x0fInitUserRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\"\x9e\x01\n" +
	"\x10InitUserResponse\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x12A\n" +
	"\x0einitialized_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\rinitializedAt\x12$\n" +
	"\tsync_code\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bsyncCode\"6\n" +
	"\x11DeleteUserRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\"r\n" +
	"\x12DeleteUserResponse\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x129\n" +
	"\n" +
	"deleted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"4\n" +
	"\x0fIsActiveRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\"\x8d\x01\n" +
	"\x10IsActiveResponse\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x12\x1b\n" +
	"\tis_active\x18\x02 \x01(\bR\bisActive\x129\n" +
	"\n" +
	"checked_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcheckedAt\"5\n" +
	"\x10IsBlockedRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\"\x90\x01\n" +
	"\x11IsBlockedResponse\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x12\x1d\n" +
	"\n" +
	"is_blocked\x18\x02 \x01(\bR\tisBlocked\x129\n" +
	"\n" +
	"checked_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcheckedAt2\xc2\x02\n" +
	"\vUserService\x12I\n" +
	"\bInitUser\x12\x1d.user.user.v1.InitUserRequest\x1a\x1e.user.user.v1.InitUserResponse\x12O\n" +
	"\n" +
	"DeleteUser\x12\x1f.user.user.v1.DeleteUserRequest\x1a .user.user.v1.DeleteUserResponse\x12I\n" +
	"\bIsActive\x12\x1d.user.user.v1.IsActiveRequest\x1a\x1e.user.user.v1.IsActiveResponse\x12L\n" +
	"\tIsBlocked\x12\x1e.user.user.v1.IsBlockedRequest\x1a\x1f.user.user.v1.IsBlockedResponseB=Z;github.com/mandacode-com/accounts-proto/user/user/v1;userv1b\x06proto3"

var (
	file_user_user_v1_user_proto_rawDescOnce sync.Once
	file_user_user_v1_user_proto_rawDescData []byte
)

func file_user_user_v1_user_proto_rawDescGZIP() []byte {
	file_user_user_v1_user_proto_rawDescOnce.Do(func() {
		file_user_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_user_v1_user_proto_rawDesc), len(file_user_user_v1_user_proto_rawDesc)))
	})
	return file_user_user_v1_user_proto_rawDescData
}

var file_user_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_user_user_v1_user_proto_goTypes = []any{
	(*InitUserRequest)(nil),       // 0: user.user.v1.InitUserRequest
	(*InitUserResponse)(nil),      // 1: user.user.v1.InitUserResponse
	(*DeleteUserRequest)(nil),     // 2: user.user.v1.DeleteUserRequest
	(*DeleteUserResponse)(nil),    // 3: user.user.v1.DeleteUserResponse
	(*IsActiveRequest)(nil),       // 4: user.user.v1.IsActiveRequest
	(*IsActiveResponse)(nil),      // 5: user.user.v1.IsActiveResponse
	(*IsBlockedRequest)(nil),      // 6: user.user.v1.IsBlockedRequest
	(*IsBlockedResponse)(nil),     // 7: user.user.v1.IsBlockedResponse
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_user_user_v1_user_proto_depIdxs = []int32{
	8, // 0: user.user.v1.InitUserResponse.initialized_at:type_name -> google.protobuf.Timestamp
	8, // 1: user.user.v1.DeleteUserResponse.deleted_at:type_name -> google.protobuf.Timestamp
	8, // 2: user.user.v1.IsActiveResponse.checked_at:type_name -> google.protobuf.Timestamp
	8, // 3: user.user.v1.IsBlockedResponse.checked_at:type_name -> google.protobuf.Timestamp
	0, // 4: user.user.v1.UserService.InitUser:input_type -> user.user.v1.InitUserRequest
	2, // 5: user.user.v1.UserService.DeleteUser:input_type -> user.user.v1.DeleteUserRequest
	4, // 6: user.user.v1.UserService.IsActive:input_type -> user.user.v1.IsActiveRequest
	6, // 7: user.user.v1.UserService.IsBlocked:input_type -> user.user.v1.IsBlockedRequest
	1, // 8: user.user.v1.UserService.InitUser:output_type -> user.user.v1.InitUserResponse
	3, // 9: user.user.v1.UserService.DeleteUser:output_type -> user.user.v1.DeleteUserResponse
	5, // 10: user.user.v1.UserService.IsActive:output_type -> user.user.v1.IsActiveResponse
	7, // 11: user.user.v1.UserService.IsBlocked:output_type -> user.user.v1.IsBlockedResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_user_user_v1_user_proto_init() }
func file_user_user_v1_user_proto_init() {
	if File_user_user_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_user_v1_user_proto_rawDesc), len(file_user_user_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_user_v1_user_proto_goTypes,
		DependencyIndexes: file_user_user_v1_user_proto_depIdxs,
		MessageInfos:      file_user_user_v1_user_proto_msgTypes,
	}.Build()
	File_user_user_v1_user_proto = out.File
	file_user_user_v1_user_proto_goTypes = nil
	file_user_user_v1_user_proto_depIdxs = nil
}
