// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: profile/v1/user.proto

package profilev1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`                       // User's email address
	SyncCode      string                 `protobuf:"bytes,3,opt,name=sync_code,json=syncCode,proto3" json:"sync_code,omitempty"` // Sync code for tracking
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitUserRequest) Reset() {
	*x = InitUserRequest{}
	mi := &file_profile_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitUserRequest) ProtoMessage() {}

func (x *InitUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitUserRequest.ProtoReflect.Descriptor instead.
func (*InitUserRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *InitUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InitUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *InitUserRequest) GetSyncCode() string {
	if x != nil {
		return x.SyncCode
	}
	return ""
}

type InitUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	InitializedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=initialized_at,json=initializedAt,proto3" json:"initialized_at,omitempty"` // User initialization timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitUserResponse) Reset() {
	*x = InitUserResponse{}
	mi := &file_profile_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitUserResponse) ProtoMessage() {}

func (x *InitUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitUserResponse.ProtoReflect.Descriptor instead.
func (*InitUserResponse) Descriptor() ([]byte, []int) {
	return file_profile_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *InitUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InitUserResponse) GetInitializedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.InitializedAt
	}
	return nil
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_profile_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"` // User deletion timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_profile_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_profile_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteUserResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type UpdateEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NewEmail      string                 `protobuf:"bytes,2,opt,name=new_email,json=newEmail,proto3" json:"new_email,omitempty"` // New email address
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailRequest) Reset() {
	*x = UpdateEmailRequest{}
	mi := &file_profile_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailRequest) ProtoMessage() {}

func (x *UpdateEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmailRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateEmailRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateEmailRequest) GetNewEmail() string {
	if x != nil {
		return x.NewEmail
	}
	return ""
}

type UpdateEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UpdatedEmail  string                 `protobuf:"bytes,2,opt,name=updated_email,json=updatedEmail,proto3" json:"updated_email,omitempty"` // Updated email address
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`          // Timestamp when the email was updated
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailResponse) Reset() {
	*x = UpdateEmailResponse{}
	mi := &file_profile_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailResponse) ProtoMessage() {}

func (x *UpdateEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailResponse.ProtoReflect.Descriptor instead.
func (*UpdateEmailResponse) Descriptor() ([]byte, []int) {
	return file_profile_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateEmailResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateEmailResponse) GetUpdatedEmail() string {
	if x != nil {
		return x.UpdatedEmail
	}
	return ""
}

func (x *UpdateEmailResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_profile_v1_user_proto protoreflect.FileDescriptor

const file_profile_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x15profile/v1/user.proto\x12\n" +
	"profile.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#third_party/validate/validate.proto\"y\n" +
	"\x0fInitUserRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x12\x1d\n" +
	"\x05email\x18\x02 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12$\n" +
	"\tsync_code\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bsyncCode\"x\n" +
	"\x10InitUserResponse\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x12A\n" +
	"\x0einitialized_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\rinitializedAt\"6\n" +
	"\x11DeleteUserRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\"r\n" +
	"\x12DeleteUserResponse\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x129\n" +
	"\n" +
	"deleted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"]\n" +
	"\x12UpdateEmailRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x12$\n" +
	"\tnew_email\x18\x02 \x01(\tB\a\xfaB\x04r\x02`\x01R\bnewEmail\"\xa1\x01\n" +
	"\x13UpdateEmailResponse\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x12,\n" +
	"\rupdated_email\x18\x02 \x01(\tB\a\xfaB\x04r\x02`\x01R\fupdatedEmail\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xf4\x01\n" +
	"\x0eProfileService\x12E\n" +
	"\bInitUser\x12\x1b.profile.v1.InitUserRequest\x1a\x1c.profile.v1.InitUserResponse\x12K\n" +
	"\n" +
	"DeleteUser\x12\x1d.profile.v1.DeleteUserRequest\x1a\x1e.profile.v1.DeleteUserResponse\x12N\n" +
	"\vUpdateEmail\x12\x1e.profile.v1.UpdateEmailRequest\x1a\x1f.profile.v1.UpdateEmailResponseB>Z<github.com/mandacode-com/accounts-proto/profile/v1;profilev1b\x06proto3"

var (
	file_profile_v1_user_proto_rawDescOnce sync.Once
	file_profile_v1_user_proto_rawDescData []byte
)

func file_profile_v1_user_proto_rawDescGZIP() []byte {
	file_profile_v1_user_proto_rawDescOnce.Do(func() {
		file_profile_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profile_v1_user_proto_rawDesc), len(file_profile_v1_user_proto_rawDesc)))
	})
	return file_profile_v1_user_proto_rawDescData
}

var file_profile_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_profile_v1_user_proto_goTypes = []any{
	(*InitUserRequest)(nil),       // 0: profile.v1.InitUserRequest
	(*InitUserResponse)(nil),      // 1: profile.v1.InitUserResponse
	(*DeleteUserRequest)(nil),     // 2: profile.v1.DeleteUserRequest
	(*DeleteUserResponse)(nil),    // 3: profile.v1.DeleteUserResponse
	(*UpdateEmailRequest)(nil),    // 4: profile.v1.UpdateEmailRequest
	(*UpdateEmailResponse)(nil),   // 5: profile.v1.UpdateEmailResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_profile_v1_user_proto_depIdxs = []int32{
	6, // 0: profile.v1.InitUserResponse.initialized_at:type_name -> google.protobuf.Timestamp
	6, // 1: profile.v1.DeleteUserResponse.deleted_at:type_name -> google.protobuf.Timestamp
	6, // 2: profile.v1.UpdateEmailResponse.updated_at:type_name -> google.protobuf.Timestamp
	0, // 3: profile.v1.ProfileService.InitUser:input_type -> profile.v1.InitUserRequest
	2, // 4: profile.v1.ProfileService.DeleteUser:input_type -> profile.v1.DeleteUserRequest
	4, // 5: profile.v1.ProfileService.UpdateEmail:input_type -> profile.v1.UpdateEmailRequest
	1, // 6: profile.v1.ProfileService.InitUser:output_type -> profile.v1.InitUserResponse
	3, // 7: profile.v1.ProfileService.DeleteUser:output_type -> profile.v1.DeleteUserResponse
	5, // 8: profile.v1.ProfileService.UpdateEmail:output_type -> profile.v1.UpdateEmailResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_profile_v1_user_proto_init() }
func file_profile_v1_user_proto_init() {
	if File_profile_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profile_v1_user_proto_rawDesc), len(file_profile_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profile_v1_user_proto_goTypes,
		DependencyIndexes: file_profile_v1_user_proto_depIdxs,
		MessageInfos:      file_profile_v1_user_proto_msgTypes,
	}.Build()
	File_profile_v1_user_proto = out.File
	file_profile_v1_user_proto_goTypes = nil
	file_profile_v1_user_proto_depIdxs = nil
}
