// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: auth/v1/user.proto

package authv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	v1 "github.com/mandacode-com/accounts-proto/go/provider/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLocalUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`       // User's email address
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"` // User's password
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLocalUserRequest) Reset() {
	*x = CreateLocalUserRequest{}
	mi := &file_auth_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLocalUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLocalUserRequest) ProtoMessage() {}

func (x *CreateLocalUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLocalUserRequest.ProtoReflect.Descriptor instead.
func (*CreateLocalUserRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLocalUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateLocalUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateLocalUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateLocalUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // User creation timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLocalUserResponse) Reset() {
	*x = CreateLocalUserResponse{}
	mi := &file_auth_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLocalUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLocalUserResponse) ProtoMessage() {}

func (x *CreateLocalUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLocalUserResponse.ProtoReflect.Descriptor instead.
func (*CreateLocalUserResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLocalUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateLocalUserResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type DeleteLocalUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLocalUserRequest) Reset() {
	*x = DeleteLocalUserRequest{}
	mi := &file_auth_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLocalUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLocalUserRequest) ProtoMessage() {}

func (x *DeleteLocalUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLocalUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteLocalUserRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteLocalUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteLocalUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"` // User deletion timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLocalUserResponse) Reset() {
	*x = DeleteLocalUserResponse{}
	mi := &file_auth_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLocalUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLocalUserResponse) ProtoMessage() {}

func (x *DeleteLocalUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLocalUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteLocalUserResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteLocalUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteLocalUserResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type UpdateLocalUserEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NewEmail      string                 `protobuf:"bytes,2,opt,name=new_email,json=newEmail,proto3" json:"new_email,omitempty"` // New email address
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLocalUserEmailRequest) Reset() {
	*x = UpdateLocalUserEmailRequest{}
	mi := &file_auth_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocalUserEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocalUserEmailRequest) ProtoMessage() {}

func (x *UpdateLocalUserEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocalUserEmailRequest.ProtoReflect.Descriptor instead.
func (*UpdateLocalUserEmailRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateLocalUserEmailRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateLocalUserEmailRequest) GetNewEmail() string {
	if x != nil {
		return x.NewEmail
	}
	return ""
}

type UpdateLocalUserEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UpdatedEmail  string                 `protobuf:"bytes,2,opt,name=updated_email,json=updatedEmail,proto3" json:"updated_email,omitempty"` // Updated email address
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`          // Timestamp when the email was updated
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLocalUserEmailResponse) Reset() {
	*x = UpdateLocalUserEmailResponse{}
	mi := &file_auth_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocalUserEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocalUserEmailResponse) ProtoMessage() {}

func (x *UpdateLocalUserEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocalUserEmailResponse.ProtoReflect.Descriptor instead.
func (*UpdateLocalUserEmailResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateLocalUserEmailResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateLocalUserEmailResponse) GetUpdatedEmail() string {
	if x != nil {
		return x.UpdatedEmail
	}
	return ""
}

func (x *UpdateLocalUserEmailResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UpdateEmailVerificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Verified      bool                   `protobuf:"varint,2,opt,name=verified,proto3" json:"verified,omitempty"` // Email verification status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailVerificationRequest) Reset() {
	*x = UpdateEmailVerificationRequest{}
	mi := &file_auth_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailVerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailVerificationRequest) ProtoMessage() {}

func (x *UpdateEmailVerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailVerificationRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmailVerificationRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateEmailVerificationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateEmailVerificationRequest) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

type UpdateEmailVerificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Verified      bool                   `protobuf:"varint,2,opt,name=verified,proto3" json:"verified,omitempty"`                   // Email verification status
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Timestamp when the email verification status was updated
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailVerificationResponse) Reset() {
	*x = UpdateEmailVerificationResponse{}
	mi := &file_auth_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailVerificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailVerificationResponse) ProtoMessage() {}

func (x *UpdateEmailVerificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailVerificationResponse.ProtoReflect.Descriptor instead.
func (*UpdateEmailVerificationResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateEmailVerificationResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateEmailVerificationResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *UpdateEmailVerificationResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateOAuthUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Provider      v1.ProviderType        `protobuf:"varint,2,opt,name=provider,proto3,enum=provider.v1.ProviderType" json:"provider,omitempty"` // OAuth provider type
	AccessToken   *string                `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3,oneof" json:"access_token,omitempty"` // OAuth access token
	Code          *string                `protobuf:"bytes,4,opt,name=code,proto3,oneof" json:"code,omitempty"`                                  // OAuth code for verification
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOAuthUserRequest) Reset() {
	*x = CreateOAuthUserRequest{}
	mi := &file_auth_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOAuthUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOAuthUserRequest) ProtoMessage() {}

func (x *CreateOAuthUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOAuthUserRequest.ProtoReflect.Descriptor instead.
func (*CreateOAuthUserRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *CreateOAuthUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOAuthUserRequest) GetProvider() v1.ProviderType {
	if x != nil {
		return x.Provider
	}
	return v1.ProviderType(0)
}

func (x *CreateOAuthUserRequest) GetAccessToken() string {
	if x != nil && x.AccessToken != nil {
		return *x.AccessToken
	}
	return ""
}

func (x *CreateOAuthUserRequest) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

type CreateOAuthUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Provider      v1.ProviderType        `protobuf:"varint,2,opt,name=provider,proto3,enum=provider.v1.ProviderType" json:"provider,omitempty"` // OAuth provider type
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`                                      // User's email address
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`             // User creation timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOAuthUserResponse) Reset() {
	*x = CreateOAuthUserResponse{}
	mi := &file_auth_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOAuthUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOAuthUserResponse) ProtoMessage() {}

func (x *CreateOAuthUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOAuthUserResponse.ProtoReflect.Descriptor instead.
func (*CreateOAuthUserResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *CreateOAuthUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOAuthUserResponse) GetProvider() v1.ProviderType {
	if x != nil {
		return x.Provider
	}
	return v1.ProviderType(0)
}

func (x *CreateOAuthUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateOAuthUserResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type DeleteOAuthUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Provider      v1.ProviderType        `protobuf:"varint,2,opt,name=provider,proto3,enum=provider.v1.ProviderType" json:"provider,omitempty"` // OAuth provider type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOAuthUserRequest) Reset() {
	*x = DeleteOAuthUserRequest{}
	mi := &file_auth_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOAuthUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOAuthUserRequest) ProtoMessage() {}

func (x *DeleteOAuthUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOAuthUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteOAuthUserRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteOAuthUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteOAuthUserRequest) GetProvider() v1.ProviderType {
	if x != nil {
		return x.Provider
	}
	return v1.ProviderType(0)
}

type DeleteOAuthUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Provider      v1.ProviderType        `protobuf:"varint,2,opt,name=provider,proto3,enum=provider.v1.ProviderType" json:"provider,omitempty"` // OAuth provider type
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`             // User deletion timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOAuthUserResponse) Reset() {
	*x = DeleteOAuthUserResponse{}
	mi := &file_auth_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOAuthUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOAuthUserResponse) ProtoMessage() {}

func (x *DeleteOAuthUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOAuthUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteOAuthUserResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_user_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteOAuthUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteOAuthUserResponse) GetProvider() v1.ProviderType {
	if x != nil {
		return x.Provider
	}
	return v1.ProviderType(0)
}

func (x *DeleteOAuthUserResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type SyncOAuthUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Provider      v1.ProviderType        `protobuf:"varint,2,opt,name=provider,proto3,enum=provider.v1.ProviderType" json:"provider,omitempty"` // OAuth provider type
	AccessToken   *string                `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3,oneof" json:"access_token,omitempty"` // OAuth access token
	Code          *string                `protobuf:"bytes,4,opt,name=code,proto3,oneof" json:"code,omitempty"`                                  // OAuth code for verification
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncOAuthUserRequest) Reset() {
	*x = SyncOAuthUserRequest{}
	mi := &file_auth_v1_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncOAuthUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOAuthUserRequest) ProtoMessage() {}

func (x *SyncOAuthUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncOAuthUserRequest.ProtoReflect.Descriptor instead.
func (*SyncOAuthUserRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_user_proto_rawDescGZIP(), []int{12}
}

func (x *SyncOAuthUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SyncOAuthUserRequest) GetProvider() v1.ProviderType {
	if x != nil {
		return x.Provider
	}
	return v1.ProviderType(0)
}

func (x *SyncOAuthUserRequest) GetAccessToken() string {
	if x != nil && x.AccessToken != nil {
		return *x.AccessToken
	}
	return ""
}

func (x *SyncOAuthUserRequest) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

type SyncOAuthUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Provider      v1.ProviderType        `protobuf:"varint,2,opt,name=provider,proto3,enum=provider.v1.ProviderType" json:"provider,omitempty"` // OAuth provider type
	SyncedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=synced_at,json=syncedAt,proto3" json:"synced_at,omitempty"`                // Timestamp when the user was synced
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncOAuthUserResponse) Reset() {
	*x = SyncOAuthUserResponse{}
	mi := &file_auth_v1_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncOAuthUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOAuthUserResponse) ProtoMessage() {}

func (x *SyncOAuthUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncOAuthUserResponse.ProtoReflect.Descriptor instead.
func (*SyncOAuthUserResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_user_proto_rawDescGZIP(), []int{13}
}

func (x *SyncOAuthUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SyncOAuthUserResponse) GetProvider() v1.ProviderType {
	if x != nil {
		return x.Provider
	}
	return v1.ProviderType(0)
}

func (x *SyncOAuthUserResponse) GetSyncedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SyncedAt
	}
	return nil
}

var File_auth_v1_user_proto protoreflect.FileDescriptor

const file_auth_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x12auth/v1/user.proto\x12\aauth.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1aprovider/v1/provider.proto\x1a#third_party/validate/validate.proto\"\x7f\n" +
	"\x16CreateLocalUserRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x12\x1d\n" +
	"\x05email\x18\x02 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12#\n" +
	"\bpassword\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\bR\bpassword\"w\n" +
	"\x17CreateLocalUserResponse\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\";\n" +
	"\x16DeleteLocalUserRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\"w\n" +
	"\x17DeleteLocalUserResponse\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x129\n" +
	"\n" +
	"deleted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"f\n" +
	"\x1bUpdateLocalUserEmailRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x12$\n" +
	"\tnew_email\x18\x02 \x01(\tB\a\xfaB\x04r\x02`\x01R\bnewEmail\"\xaa\x01\n" +
	"\x1cUpdateLocalUserEmailResponse\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x12,\n" +
	"\rupdated_email\x18\x02 \x01(\tB\a\xfaB\x04r\x02`\x01R\fupdatedEmail\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"_\n" +
	"\x1eUpdateEmailVerificationRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x12\x1a\n" +
	"\bverified\x18\x02 \x01(\bR\bverified\"\x9b\x01\n" +
	"\x1fUpdateEmailVerificationResponse\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x12\x1a\n" +
	"\bverified\x18\x02 \x01(\bR\bverified\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xdf\x01\n" +
	"\x16CreateOAuthUserRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x125\n" +
	"\bprovider\x18\x02 \x01(\x0e2\x19.provider.v1.ProviderTypeR\bprovider\x12/\n" +
	"\faccess_token\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01H\x00R\vaccessToken\x88\x01\x01\x12 \n" +
	"\x04code\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01H\x01R\x04code\x88\x01\x01B\x0f\n" +
	"\r_access_tokenB\a\n" +
	"\x05_code\"\xcd\x01\n" +
	"\x17CreateOAuthUserResponse\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x125\n" +
	"\bprovider\x18\x02 \x01(\x0e2\x19.provider.v1.ProviderTypeR\bprovider\x12\x1d\n" +
	"\x05email\x18\x03 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"r\n" +
	"\x16DeleteOAuthUserRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x125\n" +
	"\bprovider\x18\x02 \x01(\x0e2\x19.provider.v1.ProviderTypeR\bprovider\"\xae\x01\n" +
	"\x17DeleteOAuthUserResponse\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x125\n" +
	"\bprovider\x18\x02 \x01(\x0e2\x19.provider.v1.ProviderTypeR\bprovider\x129\n" +
	"\n" +
	"deleted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"\xdd\x01\n" +
	"\x14SyncOAuthUserRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x125\n" +
	"\bprovider\x18\x02 \x01(\x0e2\x19.provider.v1.ProviderTypeR\bprovider\x12/\n" +
	"\faccess_token\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01H\x00R\vaccessToken\x88\x01\x01\x12 \n" +
	"\x04code\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01H\x01R\x04code\x88\x01\x01B\x0f\n" +
	"\r_access_tokenB\a\n" +
	"\x05_code\"\xaa\x01\n" +
	"\x15SyncOAuthUserResponse\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x125\n" +
	"\bprovider\x18\x02 \x01(\x0e2\x19.provider.v1.ProviderTypeR\bprovider\x127\n" +
	"\tsynced_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bsyncedAt2\x91\x03\n" +
	"\x10LocalUserService\x12T\n" +
	"\x0fCreateLocalUser\x12\x1f.auth.v1.CreateLocalUserRequest\x1a .auth.v1.CreateLocalUserResponse\x12T\n" +
	"\x0fDeleteLocalUser\x12\x1f.auth.v1.DeleteLocalUserRequest\x1a .auth.v1.DeleteLocalUserResponse\x12c\n" +
	"\x14UpdateLocalUserEmail\x12$.auth.v1.UpdateLocalUserEmailRequest\x1a%.auth.v1.UpdateLocalUserEmailResponse\x12l\n" +
	"\x17UpdateEmailVerification\x12'.auth.v1.UpdateEmailVerificationRequest\x1a(.auth.v1.UpdateEmailVerificationResponse2\x8e\x02\n" +
	"\x10OAuthUserService\x12T\n" +
	"\x0fCreateOAuthUser\x12\x1f.auth.v1.CreateOAuthUserRequest\x1a .auth.v1.CreateOAuthUserResponse\x12T\n" +
	"\x0fDeleteOAuthUser\x12\x1f.auth.v1.DeleteOAuthUserRequest\x1a .auth.v1.DeleteOAuthUserResponse\x12N\n" +
	"\rSyncOAuthUser\x12\x1d.auth.v1.SyncOAuthUserRequest\x1a\x1e.auth.v1.SyncOAuthUserResponseB;Z9github.com/mandacode-com/accounts-proto/go/auth/v1;authv1b\x06proto3"

var (
	file_auth_v1_user_proto_rawDescOnce sync.Once
	file_auth_v1_user_proto_rawDescData []byte
)

func file_auth_v1_user_proto_rawDescGZIP() []byte {
	file_auth_v1_user_proto_rawDescOnce.Do(func() {
		file_auth_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_user_proto_rawDesc), len(file_auth_v1_user_proto_rawDesc)))
	})
	return file_auth_v1_user_proto_rawDescData
}

var file_auth_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_auth_v1_user_proto_goTypes = []any{
	(*CreateLocalUserRequest)(nil),          // 0: auth.v1.CreateLocalUserRequest
	(*CreateLocalUserResponse)(nil),         // 1: auth.v1.CreateLocalUserResponse
	(*DeleteLocalUserRequest)(nil),          // 2: auth.v1.DeleteLocalUserRequest
	(*DeleteLocalUserResponse)(nil),         // 3: auth.v1.DeleteLocalUserResponse
	(*UpdateLocalUserEmailRequest)(nil),     // 4: auth.v1.UpdateLocalUserEmailRequest
	(*UpdateLocalUserEmailResponse)(nil),    // 5: auth.v1.UpdateLocalUserEmailResponse
	(*UpdateEmailVerificationRequest)(nil),  // 6: auth.v1.UpdateEmailVerificationRequest
	(*UpdateEmailVerificationResponse)(nil), // 7: auth.v1.UpdateEmailVerificationResponse
	(*CreateOAuthUserRequest)(nil),          // 8: auth.v1.CreateOAuthUserRequest
	(*CreateOAuthUserResponse)(nil),         // 9: auth.v1.CreateOAuthUserResponse
	(*DeleteOAuthUserRequest)(nil),          // 10: auth.v1.DeleteOAuthUserRequest
	(*DeleteOAuthUserResponse)(nil),         // 11: auth.v1.DeleteOAuthUserResponse
	(*SyncOAuthUserRequest)(nil),            // 12: auth.v1.SyncOAuthUserRequest
	(*SyncOAuthUserResponse)(nil),           // 13: auth.v1.SyncOAuthUserResponse
	(*timestamppb.Timestamp)(nil),           // 14: google.protobuf.Timestamp
	(v1.ProviderType)(0),                    // 15: provider.v1.ProviderType
}
var file_auth_v1_user_proto_depIdxs = []int32{
	14, // 0: auth.v1.CreateLocalUserResponse.created_at:type_name -> google.protobuf.Timestamp
	14, // 1: auth.v1.DeleteLocalUserResponse.deleted_at:type_name -> google.protobuf.Timestamp
	14, // 2: auth.v1.UpdateLocalUserEmailResponse.updated_at:type_name -> google.protobuf.Timestamp
	14, // 3: auth.v1.UpdateEmailVerificationResponse.updated_at:type_name -> google.protobuf.Timestamp
	15, // 4: auth.v1.CreateOAuthUserRequest.provider:type_name -> provider.v1.ProviderType
	15, // 5: auth.v1.CreateOAuthUserResponse.provider:type_name -> provider.v1.ProviderType
	14, // 6: auth.v1.CreateOAuthUserResponse.created_at:type_name -> google.protobuf.Timestamp
	15, // 7: auth.v1.DeleteOAuthUserRequest.provider:type_name -> provider.v1.ProviderType
	15, // 8: auth.v1.DeleteOAuthUserResponse.provider:type_name -> provider.v1.ProviderType
	14, // 9: auth.v1.DeleteOAuthUserResponse.deleted_at:type_name -> google.protobuf.Timestamp
	15, // 10: auth.v1.SyncOAuthUserRequest.provider:type_name -> provider.v1.ProviderType
	15, // 11: auth.v1.SyncOAuthUserResponse.provider:type_name -> provider.v1.ProviderType
	14, // 12: auth.v1.SyncOAuthUserResponse.synced_at:type_name -> google.protobuf.Timestamp
	0,  // 13: auth.v1.LocalUserService.CreateLocalUser:input_type -> auth.v1.CreateLocalUserRequest
	2,  // 14: auth.v1.LocalUserService.DeleteLocalUser:input_type -> auth.v1.DeleteLocalUserRequest
	4,  // 15: auth.v1.LocalUserService.UpdateLocalUserEmail:input_type -> auth.v1.UpdateLocalUserEmailRequest
	6,  // 16: auth.v1.LocalUserService.UpdateEmailVerification:input_type -> auth.v1.UpdateEmailVerificationRequest
	8,  // 17: auth.v1.OAuthUserService.CreateOAuthUser:input_type -> auth.v1.CreateOAuthUserRequest
	10, // 18: auth.v1.OAuthUserService.DeleteOAuthUser:input_type -> auth.v1.DeleteOAuthUserRequest
	12, // 19: auth.v1.OAuthUserService.SyncOAuthUser:input_type -> auth.v1.SyncOAuthUserRequest
	1,  // 20: auth.v1.LocalUserService.CreateLocalUser:output_type -> auth.v1.CreateLocalUserResponse
	3,  // 21: auth.v1.LocalUserService.DeleteLocalUser:output_type -> auth.v1.DeleteLocalUserResponse
	5,  // 22: auth.v1.LocalUserService.UpdateLocalUserEmail:output_type -> auth.v1.UpdateLocalUserEmailResponse
	7,  // 23: auth.v1.LocalUserService.UpdateEmailVerification:output_type -> auth.v1.UpdateEmailVerificationResponse
	9,  // 24: auth.v1.OAuthUserService.CreateOAuthUser:output_type -> auth.v1.CreateOAuthUserResponse
	11, // 25: auth.v1.OAuthUserService.DeleteOAuthUser:output_type -> auth.v1.DeleteOAuthUserResponse
	13, // 26: auth.v1.OAuthUserService.SyncOAuthUser:output_type -> auth.v1.SyncOAuthUserResponse
	20, // [20:27] is the sub-list for method output_type
	13, // [13:20] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_auth_v1_user_proto_init() }
func file_auth_v1_user_proto_init() {
	if File_auth_v1_user_proto != nil {
		return
	}
	file_auth_v1_user_proto_msgTypes[8].OneofWrappers = []any{}
	file_auth_v1_user_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_user_proto_rawDesc), len(file_auth_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_auth_v1_user_proto_goTypes,
		DependencyIndexes: file_auth_v1_user_proto_depIdxs,
		MessageInfos:      file_auth_v1_user_proto_msgTypes,
	}.Build()
	File_auth_v1_user_proto = out.File
	file_auth_v1_user_proto_goTypes = nil
	file_auth_v1_user_proto_depIdxs = nil
}
