// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: provider/v1/provider.proto

package providerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProviderType int32

const (
	ProviderType_PROVIDER_TYPE_UNSPECIFIED ProviderType = 0 // Unspecified provider type
	ProviderType_PROVIDER_TYPE_GOOGLE      ProviderType = 1 // Google OAuth provider
	ProviderType_PROVIDER_TYPE_KAKAO       ProviderType = 2 // Kakao OAuth provider
	ProviderType_PROVIDER_TYPE_NAVER       ProviderType = 3 // Naver OAuth provider
	ProviderType_PROVIDER_TYPE_APPLE       ProviderType = 4 // Apple OAuth provider
	ProviderType_PROVIDER_TYPE_GITHUB      ProviderType = 5 // GitHub OAuth provider
	ProviderType_PROVIDER_TYPE_GITLAB      ProviderType = 6 // GitLab OAuth provider
	ProviderType_PROVIDER_TYPE_FACEBOOK    ProviderType = 7 // Facebook OAuth provider
)

// Enum value maps for ProviderType.
var (
	ProviderType_name = map[int32]string{
		0: "PROVIDER_TYPE_UNSPECIFIED",
		1: "PROVIDER_TYPE_GOOGLE",
		2: "PROVIDER_TYPE_KAKAO",
		3: "PROVIDER_TYPE_NAVER",
		4: "PROVIDER_TYPE_APPLE",
		5: "PROVIDER_TYPE_GITHUB",
		6: "PROVIDER_TYPE_GITLAB",
		7: "PROVIDER_TYPE_FACEBOOK",
	}
	ProviderType_value = map[string]int32{
		"PROVIDER_TYPE_UNSPECIFIED": 0,
		"PROVIDER_TYPE_GOOGLE":      1,
		"PROVIDER_TYPE_KAKAO":       2,
		"PROVIDER_TYPE_NAVER":       3,
		"PROVIDER_TYPE_APPLE":       4,
		"PROVIDER_TYPE_GITHUB":      5,
		"PROVIDER_TYPE_GITLAB":      6,
		"PROVIDER_TYPE_FACEBOOK":    7,
	}
)

func (x ProviderType) Enum() *ProviderType {
	p := new(ProviderType)
	*p = x
	return p
}

func (x ProviderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderType) Descriptor() protoreflect.EnumDescriptor {
	return file_provider_v1_provider_proto_enumTypes[0].Descriptor()
}

func (ProviderType) Type() protoreflect.EnumType {
	return &file_provider_v1_provider_proto_enumTypes[0]
}

func (x ProviderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderType.Descriptor instead.
func (ProviderType) EnumDescriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{0}
}

var File_provider_v1_provider_proto protoreflect.FileDescriptor

const file_provider_v1_provider_proto_rawDesc = "" +
	"\n" +
	"\x1aprovider/v1/provider.proto\x12\vprovider.v1*\xe2\x01\n" +
	"\fProviderType\x12\x1d\n" +
	"\x19PROVIDER_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PROVIDER_TYPE_GOOGLE\x10\x01\x12\x17\n" +
	"\x13PROVIDER_TYPE_KAKAO\x10\x02\x12\x17\n" +
	"\x13PROVIDER_TYPE_NAVER\x10\x03\x12\x17\n" +
	"\x13PROVIDER_TYPE_APPLE\x10\x04\x12\x18\n" +
	"\x14PROVIDER_TYPE_GITHUB\x10\x05\x12\x18\n" +
	"\x14PROVIDER_TYPE_GITLAB\x10\x06\x12\x1a\n" +
	"\x16PROVIDER_TYPE_FACEBOOK\x10\aBCZAgithub.com/mandacode-com/accounts-proto/go/provider/v1;providerv1b\x06proto3"

var (
	file_provider_v1_provider_proto_rawDescOnce sync.Once
	file_provider_v1_provider_proto_rawDescData []byte
)

func file_provider_v1_provider_proto_rawDescGZIP() []byte {
	file_provider_v1_provider_proto_rawDescOnce.Do(func() {
		file_provider_v1_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_provider_v1_provider_proto_rawDesc), len(file_provider_v1_provider_proto_rawDesc)))
	})
	return file_provider_v1_provider_proto_rawDescData
}

var file_provider_v1_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_provider_v1_provider_proto_goTypes = []any{
	(ProviderType)(0), // 0: provider.v1.ProviderType
}
var file_provider_v1_provider_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_provider_v1_provider_proto_init() }
func file_provider_v1_provider_proto_init() {
	if File_provider_v1_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_provider_v1_provider_proto_rawDesc), len(file_provider_v1_provider_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_provider_v1_provider_proto_goTypes,
		DependencyIndexes: file_provider_v1_provider_proto_depIdxs,
		EnumInfos:         file_provider_v1_provider_proto_enumTypes,
	}.Build()
	File_provider_v1_provider_proto = out.File
	file_provider_v1_provider_proto_goTypes = nil
	file_provider_v1_provider_proto_depIdxs = nil
}
